sudo: required

services:
  - docker

branches:
  only:
    - master

install:
  - docker build -t hnakamur/highwayrpm .

script:
  - docker run hnakamur/highwayrpm "$COPR_LOGIN" "$COPR_USERNAME" "$COPR_TOKEN"
